/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Collection {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "schema")]
    pub schema: ::std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "updated")]
    pub updated: Option<String>,
    #[serde(rename = "indexed")]
    pub indexed: Option<String>,
}

impl Collection {
    pub fn new(
        id: i32,
        name: String,
        schema: ::std::collections::HashMap<String, serde_json::Value>,
        created: String,
        updated: Option<String>,
        indexed: Option<String>,
    ) -> Collection {
        Collection {
            id,
            name,
            schema,
            created,
            updated,
            indexed,
        }
    }
}
