/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionContentsDocumentsRequest {
    #[serde(rename = "collectionId")]
    pub collection_id: i32,
    #[serde(rename = "contentsFields")]
    pub contents_fields: Vec<crate::models::ContentsField>,
    #[serde(rename = "docMetadataFieldnames")]
    pub doc_metadata_fieldnames: Vec<String>,
}

impl CollectionContentsDocumentsRequest {
    pub fn new(
        collection_id: i32,
        contents_fields: Vec<crate::models::ContentsField>,
        doc_metadata_fieldnames: Vec<String>,
    ) -> CollectionContentsDocumentsRequest {
        CollectionContentsDocumentsRequest {
            collection_id,
            contents_fields,
            doc_metadata_fieldnames,
        }
    }
}
