/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionContentsResponse {
    #[serde(rename = "root")]
    pub root: Box<crate::models::CollectionNode>,
}

impl CollectionContentsResponse {
    pub fn new(
        root: crate::models::CollectionNode,
    ) -> CollectionContentsResponse {
        CollectionContentsResponse {
            root: Box::new(root),
        }
    }
}
