/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionContentsDocumentsResponse {
    #[serde(rename = "documents")]
    pub documents: Vec<crate::models::CollectionContentsDocument>,
}

impl CollectionContentsDocumentsResponse {
    pub fn new(
        documents: Vec<crate::models::CollectionContentsDocument>,
    ) -> CollectionContentsDocumentsResponse {
        CollectionContentsDocumentsResponse { documents }
    }
}
