/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCollectionRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "schema")]
    pub schema: ::std::collections::HashMap<String, serde_json::Value>,
}

impl CreateCollectionRequest {
    pub fn new(
        name: String,
        schema: ::std::collections::HashMap<String, serde_json::Value>,
    ) -> CreateCollectionRequest {
        CreateCollectionRequest { name, schema }
    }
}
