/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAdminRequest {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(
        rename = "passwordCrypto",
        skip_serializing_if = "Option::is_none"
    )]
    pub password_crypto: Option<String>,
    #[serde(rename = "passwordSalt", skip_serializing_if = "Option::is_none")]
    pub password_salt: Option<String>,
    #[serde(rename = "passwordHash", skip_serializing_if = "Option::is_none")]
    pub password_hash: Option<String>,
    #[serde(rename = "fullname")]
    pub fullname: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "roles")]
    pub roles: Vec<i32>,
}

impl CreateAdminRequest {
    pub fn new(
        username: String,
        fullname: String,
        email: String,
        roles: Vec<i32>,
    ) -> CreateAdminRequest {
        CreateAdminRequest {
            username,
            password: None,
            password_crypto: None,
            password_salt: None,
            password_hash: None,
            fullname,
            email,
            roles,
        }
    }
}
