/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRoleRequest {
    #[serde(rename = "defaultScope", skip_serializing_if = "Option::is_none")]
    pub default_scope: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "claims", skip_serializing_if = "Option::is_none")]
    pub claims: Option<Vec<String>>,
}

impl CreateRoleRequest {
    pub fn new(name: String) -> CreateRoleRequest {
        CreateRoleRequest {
            default_scope: None,
            name,
            claims: None,
        }
    }
}
