/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUserRequest {
    #[serde(rename = "status")]
    pub status: crate::models::UserStatus,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "fullname")]
    pub fullname: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "roles")]
    pub roles: Vec<i32>,
    #[serde(rename = "profiles")]
    pub profiles: Vec<i32>,
    #[serde(rename = "collections")]
    pub collections: Vec<i32>,
    #[serde(rename = "denyCollections")]
    pub deny_collections: Vec<i32>,
    #[serde(rename = "customFields")]
    pub custom_fields: ::std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "appName")]
    pub app_name: Option<String>,
    #[serde(rename = "appMetadata", skip_serializing_if = "Option::is_none")]
    pub app_metadata:
        Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl CreateUserRequest {
    pub fn new(
        status: crate::models::UserStatus,
        username: String,
        password: String,
        fullname: String,
        email: String,
        roles: Vec<i32>,
        profiles: Vec<i32>,
        collections: Vec<i32>,
        deny_collections: Vec<i32>,
        custom_fields: ::std::collections::HashMap<String, serde_json::Value>,
        app_name: Option<String>,
    ) -> CreateUserRequest {
        CreateUserRequest {
            status,
            username,
            password,
            fullname,
            email,
            roles,
            profiles,
            collections,
            deny_collections,
            custom_fields,
            app_name,
            app_metadata: None,
        }
    }
}
