/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateProfileRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "collections")]
    pub collections: Vec<i32>,
}

impl CreateProfileRequest {
    pub fn new(name: String, collections: Vec<i32>) -> CreateProfileRequest {
        CreateProfileRequest { name, collections }
    }
}
