/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Document {
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "filename")]
    pub filename: String,
}

impl Document {
    pub fn new(signature: String, filename: String) -> Document {
        Document {
            signature,
            filename,
        }
    }
}
