/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DocumentUpdate {
    #[serde(rename = "doc")]
    pub doc: Box<crate::models::Document>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "docMetadata")]
    pub doc_metadata: ::std::collections::HashMap<String, String>,
    #[serde(rename = "attachments")]
    pub attachments: Vec<crate::models::Document>,
}

impl DocumentUpdate {
    pub fn new(
        doc: crate::models::Document,
        title: String,
        doc_metadata: ::std::collections::HashMap<String, String>,
        attachments: Vec<crate::models::Document>,
    ) -> DocumentUpdate {
        DocumentUpdate {
            doc: Box::new(doc),
            title,
            doc_metadata,
            attachments,
        }
    }
}
