/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportUsersResponse {
    #[serde(rename = "tenant")]
    pub tenant: String,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "stage")]
    pub stage: String,
    #[serde(rename = "exported")]
    pub exported: String,
    #[serde(rename = "users")]
    pub users: Vec<crate::models::ExportedUser>,
}

impl ExportUsersResponse {
    pub fn new(
        tenant: String,
        version: String,
        stage: String,
        exported: String,
        users: Vec<crate::models::ExportedUser>,
    ) -> ExportUsersResponse {
        ExportUsersResponse {
            tenant,
            version,
            stage,
            exported,
            users,
        }
    }
}
