/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct G4AuthAuthMessage {
    #[serde(rename = "validCredentials")]
    pub valid_credentials: bool,
    #[serde(rename = "accessAllowed")]
    pub access_allowed: bool,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "host")]
    pub host: String,
}

impl G4AuthAuthMessage {
    pub fn new(
        valid_credentials: bool,
        access_allowed: bool,
        username: String,
        host: String,
    ) -> G4AuthAuthMessage {
        G4AuthAuthMessage {
            valid_credentials,
            access_allowed,
            username,
            host,
        }
    }
}
