/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct G4CollectionLoadedMessage {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "name")]
    pub name: String,
}

impl G4CollectionLoadedMessage {
    pub fn new(count: i32, name: String) -> G4CollectionLoadedMessage {
        G4CollectionLoadedMessage { count, name }
    }
}
