/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct G4DocumentLoadedMessage {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "docId")]
    pub doc_id: i64,
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "docType")]
    pub doc_type: Option<String>,
    #[serde(rename = "filename")]
    pub filename: Option<String>,
    #[serde(rename = "loaded")]
    pub loaded: Option<String>,
    #[serde(rename = "policies")]
    pub policies: Vec<String>,
    #[serde(rename = "jobId")]
    pub job_id: Option<String>,
}

impl G4DocumentLoadedMessage {
    pub fn new(
        username: String,
        doc_id: i64,
        signature: String,
        doc_type: Option<String>,
        filename: Option<String>,
        loaded: Option<String>,
        policies: Vec<String>,
        job_id: Option<String>,
    ) -> G4DocumentLoadedMessage {
        G4DocumentLoadedMessage {
            username,
            doc_id,
            signature,
            doc_type,
            filename,
            loaded,
            policies,
            job_id,
        }
    }
}
