/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct G4SessionCloseMessage {
    #[serde(rename = "sessionId")]
    pub session_id: String,
    #[serde(rename = "host")]
    pub host: String,
}

impl G4SessionCloseMessage {
    pub fn new(session_id: String, host: String) -> G4SessionCloseMessage {
        G4SessionCloseMessage { session_id, host }
    }
}
