/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct G4SessionFailMessage {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "host")]
    pub host: String,
}

impl G4SessionFailMessage {
    pub fn new(username: String, host: String) -> G4SessionFailMessage {
        G4SessionFailMessage { username, host }
    }
}
