/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct G4TenantArchiveMessage {
    #[serde(rename = "tenantId")]
    pub tenant_id: i32,
}

impl G4TenantArchiveMessage {
    pub fn new(tenant_id: i32) -> G4TenantArchiveMessage {
        G4TenantArchiveMessage { tenant_id }
    }
}
