/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct G4TenantCreateMessage {
    #[serde(rename = "tenantId")]
    pub tenant_id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: Option<String>,
}

impl G4TenantCreateMessage {
    pub fn new(
        tenant_id: i32,
        name: String,
        description: Option<String>,
    ) -> G4TenantCreateMessage {
        G4TenantCreateMessage {
            tenant_id,
            name,
            description,
        }
    }
}
