/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct G4UserCreateMessage {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "host")]
    pub host: String,
}

impl G4UserCreateMessage {
    pub fn new(username: String, id: i32, host: String) -> G4UserCreateMessage {
        G4UserCreateMessage { username, id, host }
    }
}
