/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUserEventsResponse {
    #[serde(rename = "request")]
    pub request: Box<crate::models::GetUserEventsRequest>,
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "events")]
    pub events: Vec<crate::models::RetrievedUserEvent>,
}

impl GetUserEventsResponse {
    pub fn new(
        request: crate::models::GetUserEventsRequest,
        total: i32,
        events: Vec<crate::models::RetrievedUserEvent>,
    ) -> GetUserEventsResponse {
        GetUserEventsResponse {
            request: Box::new(request),
            total,
            events,
        }
    }
}
