/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUsersWithAppMetadataResponse {
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "contains")]
    pub contains: Option<String>,
    #[serde(rename = "skip")]
    pub skip: Option<i32>,
    #[serde(rename = "take")]
    pub take: Option<i32>,
    #[serde(rename = "archived")]
    pub archived: Option<bool>,
    #[serde(rename = "users")]
    pub users: Vec<crate::models::UserWithAppMetadata>,
}

impl GetUsersWithAppMetadataResponse {
    pub fn new(
        total: i32,
        contains: Option<String>,
        skip: Option<i32>,
        take: Option<i32>,
        archived: Option<bool>,
        users: Vec<crate::models::UserWithAppMetadata>,
    ) -> GetUsersWithAppMetadataResponse {
        GetUsersWithAppMetadataResponse {
            total,
            contains,
            skip,
            take,
            archived,
            users,
        }
    }
}
