/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTenantResponse {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "created")]
    pub created: String,
    #[serde(rename = "description")]
    pub description: Option<String>,
    #[serde(rename = "repository")]
    pub repository: String,
    #[serde(rename = "activeUsers")]
    pub active_users: ::std::collections::HashMap<String, i32>,
    #[serde(rename = "archivedUsers")]
    pub archived_users: ::std::collections::HashMap<String, i32>,
    #[serde(rename = "userEvents")]
    pub user_events: ::std::collections::HashMap<String, i32>,
    #[serde(rename = "firstEvent")]
    pub first_event: Option<String>,
    #[serde(rename = "lastEvent")]
    pub last_event: Option<String>,
}

impl GetTenantResponse {
    pub fn new(
        id: i32,
        name: String,
        created: String,
        description: Option<String>,
        repository: String,
        active_users: ::std::collections::HashMap<String, i32>,
        archived_users: ::std::collections::HashMap<String, i32>,
        user_events: ::std::collections::HashMap<String, i32>,
        first_event: Option<String>,
        last_event: Option<String>,
    ) -> GetTenantResponse {
        GetTenantResponse {
            id,
            name,
            created,
            description,
            repository,
            active_users,
            archived_users,
            user_events,
            first_event,
            last_event,
        }
    }
}
