/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTenantsResponse {
    #[serde(rename = "tenants")]
    pub tenants: Vec<crate::models::GetTenantResponse>,
}

impl GetTenantsResponse {
    pub fn new(
        tenants: Vec<crate::models::GetTenantResponse>,
    ) -> GetTenantsResponse {
        GetTenantsResponse { tenants }
    }
}
