/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUsersRequest {
    #[serde(rename = "appName", skip_serializing_if = "Option::is_none")]
    pub app_name: Option<String>,
    #[serde(rename = "contains", skip_serializing_if = "Option::is_none")]
    pub contains: Option<String>,
    #[serde(rename = "skip", skip_serializing_if = "Option::is_none")]
    pub skip: Option<i32>,
    #[serde(rename = "take", skip_serializing_if = "Option::is_none")]
    pub take: Option<i32>,
    #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
    pub archived: Option<bool>,
}

impl GetUsersRequest {
    pub fn new() -> GetUsersRequest {
        GetUsersRequest {
            app_name: None,
            contains: None,
            skip: None,
            take: None,
            archived: None,
        }
    }
}
