/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAdminsResponse {
    #[serde(rename = "admins", skip_serializing_if = "Option::is_none")]
    pub admins: Option<Vec<crate::models::AdminUser>>,
}

impl GetAdminsResponse {
    pub fn new() -> GetAdminsResponse {
        GetAdminsResponse { admins: None }
    }
}
