/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRolesResponse {
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
    #[serde(rename = "roles")]
    pub roles: Vec<crate::models::RoleResponse>,
}

impl GetRolesResponse {
    pub fn new(
        scopes: Vec<String>,
        roles: Vec<crate::models::RoleResponse>,
    ) -> GetRolesResponse {
        GetRolesResponse { scopes, roles }
    }
}
