/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProfilesResponse {
    #[serde(rename = "profiles")]
    pub profiles: Vec<crate::models::GetProfileResponse>,
}

impl GetProfilesResponse {
    pub fn new(
        profiles: Vec<crate::models::GetProfileResponse>,
    ) -> GetProfilesResponse {
        GetProfilesResponse { profiles }
    }
}
