/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCollectionsResponse {
    #[serde(rename = "collections")]
    pub collections: Vec<crate::models::Collection>,
}

impl GetCollectionsResponse {
    pub fn new(
        collections: Vec<crate::models::Collection>,
    ) -> GetCollectionsResponse {
        GetCollectionsResponse { collections }
    }
}
