/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImportUsersResponse {
    #[serde(rename = "importErrors")]
    pub import_errors: i32,
    #[serde(rename = "usersImported")]
    pub users_imported: i32,
    #[serde(rename = "errors")]
    pub errors: Vec<String>,
    #[serde(rename = "imports")]
    pub imports: Vec<String>,
}

impl ImportUsersResponse {
    pub fn new(
        import_errors: i32,
        users_imported: i32,
        errors: Vec<String>,
        imports: Vec<String>,
    ) -> ImportUsersResponse {
        ImportUsersResponse {
            import_errors,
            users_imported,
            errors,
            imports,
        }
    }
}
