/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImportUsersRequest {
    #[serde(rename = "tenant")]
    pub tenant: String,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "users")]
    pub users: Vec<crate::models::ExportedUser>,
}

impl ImportUsersRequest {
    pub fn new(
        tenant: String,
        version: String,
        users: Vec<crate::models::ExportedUser>,
    ) -> ImportUsersRequest {
        ImportUsersRequest {
            tenant,
            version,
            users,
        }
    }
}
