/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImportUserResponse {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "bearer")]
    pub bearer: String,
}

impl ImportUserResponse {
    pub fn new(id: i32, bearer: String) -> ImportUserResponse {
        ImportUserResponse { id, bearer }
    }
}
