/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoadDocumentRequest {
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "docType")]
    pub doc_type: String,
    #[serde(rename = "filename", skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    #[serde(rename = "policies")]
    pub policies: Vec<String>,
    #[serde(rename = "parts", skip_serializing_if = "Option::is_none")]
    pub parts: Option<i32>,
}

impl LoadDocumentRequest {
    pub fn new(
        signature: String,
        doc_type: String,
        policies: Vec<String>,
    ) -> LoadDocumentRequest {
        LoadDocumentRequest {
            signature,
            doc_type,
            filename: None,
            policies,
            parts: None,
        }
    }
}
