/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoadDocumentResponse {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "signedUploadUrls")]
    pub signed_upload_urls: Vec<String>,
    #[serde(rename = "bearer")]
    pub bearer: String,
}

impl LoadDocumentResponse {
    pub fn new(
        id: i64,
        signed_upload_urls: Vec<String>,
        bearer: String,
    ) -> LoadDocumentResponse {
        LoadDocumentResponse {
            id,
            signed_upload_urls,
            bearer,
        }
    }
}
