/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PasswordPolicy {
    #[serde(rename = "minLength", skip_serializing_if = "Option::is_none")]
    pub min_length: Option<i32>,
    #[serde(rename = "minNumeric", skip_serializing_if = "Option::is_none")]
    pub min_numeric: Option<i32>,
    #[serde(rename = "minUpperCase", skip_serializing_if = "Option::is_none")]
    pub min_upper_case: Option<i32>,
    #[serde(rename = "minLowerCase", skip_serializing_if = "Option::is_none")]
    pub min_lower_case: Option<i32>,
    #[serde(
        rename = "minNonAlphanumeric",
        skip_serializing_if = "Option::is_none"
    )]
    pub min_non_alphanumeric: Option<i32>,
}

impl PasswordPolicy {
    pub fn new() -> PasswordPolicy {
        PasswordPolicy {
            min_length: None,
            min_numeric: None,
            min_upper_case: None,
            min_lower_case: None,
            min_non_alphanumeric: None,
        }
    }
}
