/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PasswordChangeRequest {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "newPassword")]
    pub new_password: String,
}

impl PasswordChangeRequest {
    pub fn new(
        username: String,
        password: String,
        new_password: String,
    ) -> PasswordChangeRequest {
        PasswordChangeRequest {
            username,
            password,
            new_password,
        }
    }
}
