/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefreshResponse {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "claims")]
    pub claims: Vec<String>,
    #[serde(rename = "bearer")]
    pub bearer: String,
}

impl RefreshResponse {
    pub fn new(
        username: String,
        claims: Vec<String>,
        bearer: String,
    ) -> RefreshResponse {
        RefreshResponse {
            username,
            claims,
            bearer,
        }
    }
}
