/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCollectionResponse {
    #[serde(rename = "collectionId")]
    pub collection_id: i32,
    #[serde(rename = "status")]
    pub status: Vec<crate::models::UpdateStatus>,
}

impl UpdateCollectionResponse {
    pub fn new(
        collection_id: i32,
        status: Vec<crate::models::UpdateStatus>,
    ) -> UpdateCollectionResponse {
        UpdateCollectionResponse {
            collection_id,
            status,
        }
    }
}
