/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCollectionRequest {
    #[serde(rename = "collectionId")]
    pub collection_id: i32,
    #[serde(rename = "update")]
    pub update: Vec<crate::models::DocumentUpdate>,
    #[serde(rename = "archive")]
    pub archive: Vec<String>,
}

impl UpdateCollectionRequest {
    pub fn new(
        collection_id: i32,
        update: Vec<crate::models::DocumentUpdate>,
        archive: Vec<String>,
    ) -> UpdateCollectionRequest {
        UpdateCollectionRequest {
            collection_id,
            update,
            archive,
        }
    }
}
