/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateStatus {
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "filename")]
    pub filename: Option<String>,
    #[serde(rename = "failed")]
    pub failed: bool,
    #[serde(rename = "message")]
    pub message: String,
}

impl UpdateStatus {
    pub fn new(
        signature: String,
        filename: Option<String>,
        failed: bool,
        message: String,
    ) -> UpdateStatus {
        UpdateStatus {
            signature,
            filename,
            failed,
            message,
        }
    }
}
