/*
 * G4 API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRoleRequest {
    #[serde(rename = "defaultScope", skip_serializing_if = "Option::is_none")]
    pub default_scope: Option<String>,
    #[serde(rename = "newName", skip_serializing_if = "Option::is_none")]
    pub new_name: Option<String>,
    #[serde(rename = "claims", skip_serializing_if = "Option::is_none")]
    pub claims: Option<Vec<String>>,
}

impl UpdateRoleRequest {
    pub fn new() -> UpdateRoleRequest {
        UpdateRoleRequest {
            default_scope: None,
            new_name: None,
            claims: None,
        }
    }
}
